### ISSUE TITLE
ios - Single sign-on

### ISSUE THREAD

**Issue by cmcaboy** [gilroman/react-native-expo-facebook-and-firebase-login#1]
I am using the same approach, yet users on ios get prompted to enter their facebook credentials each time they login. Android does not have this problem.

Is this the same case with you?

**Comment by gilroman** [comment]
In my iOS app, once a user Signs In with their facebook credentials they remain signed in until they hit the Sign Out button.  Users don't have to keep signing in every time they start the app.
